language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Kotlin (JDK 1.8)"
      script: cd $TRAVIS_BUILD_DIR/junit5-jupiter-starter-maven-kotlin && ./mvnw -f ./pom-java8.xml test
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Kotlin (JDK 11)"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR/junit5-jupiter-starter-maven-kotlin && ./mvnw test
cache:
  directories:
    - ~/.m2
